service: 'hikick-carchap-sync'

provider:
  name: aws
  runtime: nodejs12.x
  profile: hikick
  region: ap-northeast-2
  stage: prod
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: get
